const greekAlphabet = [
    { character: 'α', title: 'Alpha' },
    { character: 'β', title: 'Beta' },
    { character: 'γ', title: 'Gamma' },
    { character: 'δ', title: 'Delta' },
    { character: 'ε', title: 'Epsilon' },
    { character: 'ζ', title: 'Zeta' },
    { character: 'η', title: 'Eta' },
    { character: 'θ', title: 'Theta' },
    { character: 'ι', title: 'Iota' },
    { character: 'κ', title: 'Kappa' },
    { character: 'λ', title: 'Lambda' },
    { character: 'μ', title: 'Mu' },
    { character: 'ν', title: 'Nu' },
    { character: 'ξ', title: 'Xi' },
    { character: 'ο', title: 'Omicron' },
    { character: 'π', title: 'Pi' },
    { character: 'ρ', title: 'Rho' },
    { character: 'σ', title: 'Sigma' },
    { character: 'τ', title: 'Tau' },
    { character: 'υ', title: 'Upsilon' },
    { character: 'φ', title: 'Phi' },
    { character: 'χ', title: 'Chi' },
    { character: 'ψ', title: 'Psi' },
    { character: 'ω', title: 'Omega' },
    { character: 'Α', title: 'Alpha' },
    { character: 'Β', title: 'Beta' },
    { character: 'Γ', title: 'Gamma' },
    { character: 'Δ', title: 'Delta' },
    { character: 'Ε', title: 'Epsilon' },
    { character: 'Ζ', title: 'Zeta' },
    { character: 'Η', title: 'Eta' },
    { character: 'Θ', title: 'Theta' },
    { character: 'Ι', title: 'Iota' },
    { character: 'Κ', title: 'Kappa' },
    { character: 'Λ', title: 'Lambda' },
    { character: 'Μ', title: 'Mu' },
    { character: 'Ν', title: 'Nu' },
    { character: 'Ξ', title: 'Xi' },
    { character: 'Ο', title: 'Omicron' },
    { character: 'Π', title: 'Pi' },
    { character: 'Ρ', title: 'Rho' },
    { character: 'Σ', title: 'Sigma' },
    { character: 'Τ', title: 'Tau' },
    { character: 'Υ', title: 'Upsilon' },
    { character: 'Φ', title: 'Phi' },
    { character: 'Χ', title: 'Chi' },
    { character: 'Ψ', title: 'Psi' },
    { character: 'Ω', title: 'Omega' }
];

export const greekAlphabetForEditor = [
    { character: 'Α', title: 'Alpha' },
    { character: 'β', title: 'Beta' },
    { character: 'γ', title: 'Gamma' },
    { character: 'δ', title: 'Delta' },
    { character: 'ε', title: 'Epsilon' },
    { character: 'ζ', title: 'Zeta' },
    { character: 'η', title: 'Eta' },
    { character: 'θ', title: 'Theta' },
    { character: 'ι', title: 'Iota' },
    { character: 'κ', title: 'Kappa' },
    { character: 'λ', title: 'Lambda' },
    { character: 'μ', title: 'Mu' },
    { character: 'ν', title: 'Nu' },
    { character: 'ξ', title: 'Xi' },
    { character: 'ο', title: 'Omicron' },
    { character: 'π', title: 'Pi' },
    { character: 'ρ', title: 'Rho' },
    { character: 'σ', title: 'Sigma' },
    { character: 'τ', title: 'Tau' },
    { character: 'υ', title: 'Upsilon' },
    { character: 'φ', title: 'Phi' },
    { character: 'χ', title: 'Chi' },
    { character: 'ψ', title: 'Psi' },
    { character: 'ω', title: 'Omega' },
];

export const mathSymbolsForEditor = [
    { character: "∅", title: ("Empty set") },
    { character: "±", title: ("Plus-minus sign") },
    { character: "∗", title: ("Asterisk operator") },
    { character: "≥", title: ("Greater-than or equal to") },
    { character: "≤", title: ("Less-than or equal to") },
    { character: "≠", title: ("Not equal to") },
    { character: "⊥", title: ("") },
    { character: "∞", title: ("Infinity") },
    { character: "≈", title: ("Almost equal to") },
    { character: "∼", title: ("Tilde operator") },
    { character: "∫", title: ("Integral") },
    { character: "√", title: ("Square root") },
    { character: "∑", title: ("N-ary summation") },
    { character: "△", title: ("") },
    { character: "□", title: ("") },
  ];


 export const customSpecialCharacters = [{
    groupName:  "Mathematical", items: mathSymbolsForEditor}
      ,
      {
        groupName:  "Greek", items: greekAlphabetForEditor
      
      }]
